# Generated by Django 5.1.6 on 2026-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ da Empresa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('complement', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Alternativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição, resumo, valores')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Homologada pelo PAT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
