# Generated by Django 5.1.6 on 2026-05-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ da Empresa')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('complement', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Alternativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição, resumo, valores')),
                ('logo', models.FileField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logotipo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Homologada pelo PAT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Cargo')),
                ('type_of_contract', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Estágio'), ('TEMPORARY', 'Temporário')], default='CLT', max_length=20, verbose_name='Tipo de Contrato')),
                ('description', models.TextField(verbose_name='Descrição da Vaga')),
                ('location', models.CharField(default='Jacareí - SP', max_length=150, verbose_name='Localidade')),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade de Vagas')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Publicado'), ('FINALIZED', 'Finalizado'), ('ARCHIVED', 'Arquivado'), ('DELETED', 'Deletado'), ('EVALUATION', 'Em Avaliação')], default='EVALUATION', max_length=20, verbose_name='Status da Vaga')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Externo')),
                ('ref_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Referência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
