# Generated by Django 5.1.6 on 2026-05-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('arquivado', 'Arquivado'), ('deletado', 'Deletado'), ('avaliacao', 'Avaliação')], default='avaliacao', max_length=20, verbose_name='Status da Vaga'),
        ),
    ]
