# Generated by Django 5.1.6 on 2026-05-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_company_logo_alter_job_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Alternative Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='Company CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description, Summary, Values'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified by PAT'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='External Link'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Jacareí - SP', max_length=150, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Vacancy Quantity'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ref_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reference Email'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('finalized', 'Finalized'), ('archived', 'Archived'), ('deleted', 'Deleted'), ('evaluation', 'Evaluation')], default='evaluation', max_length=20, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type_of_contract',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship'), ('TEMPORARY', 'Temporary')], default='CLT', max_length=20, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
