# Generated by Django 5.1.6 on 2026-05-29 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Alternativo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição, resumo, valores'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Homologada pelo PAT'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da Empresa'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criada em'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Descrição da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Externo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Jacareí - SP', max_length=150, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='job',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade de Vagas'),
        ),
        migrations.AlterField(
            model_name='job',
            name='ref_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Referência'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('published', 'Publicado'), ('finalized', 'Finalizado'), ('archived', 'Arquivado'), ('deleted', 'Deletado'), ('evaluation', 'Em Avaliação')], default='evaluation', max_length=20, verbose_name='Status da Vaga'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type_of_contract',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Estágio'), ('TEMPORARY', 'Temporário')], default='CLT', max_length=20, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizada em'),
        ),
    ]
