# Generated by Django 5.1.6 on 2026-05-31 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0004_alter_company_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
