# Generated by Django 5.1.6 on 2026-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_candidacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='clicks_count',
            field=models.IntegerField(default=0, verbose_name='Cliques'),
        ),
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
