# Generated by Django 5.1.6 on 2026-06-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_password'),
        ('jobs', '0007_job_clicks_count_job_views_count'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type_of_contract', 'CLT'), _negated=True), ('salary__gte', 1412.0), _connector='OR'), name='clt_salary_min_wage'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='job_quantity_min_one'),
        ),
    ]
